### User sing up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
  "name": "Jane Doe",
  "company": "XYZ Limited",
  "address": "Some Address Nairobi",
  "phone": "7824568942",
  "email": "jane.doe@gmail.com",
  "password": "12345678"
}

### User sing in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
  "email": "jane.doe@gmail.com",
  "password": "12345678"   
}

### Get a user profile endpoint
GET  http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQGdtYWlsLmNvbSIsImlhdCI6MTYzNzg2MDMwOSwiZXhwIjoxNjM3ODYwMzY5fQ.ZhpzOk_9t22PMY6w70fqMfn0s47Fx9roGCIKQnJVz-A


###Token routers

### Get refreshed token
GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQGdtYWlsLmNvbSIsImlhdCI6MTYzNzg2MDMwOSwiZXhwIjoxNjQwNDUyMzA5fQ.vwUeGqr1EK6jtj5M0RCkBah-t04HrGdW15t6p_itV6Y

#### Password reset endpoints
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json 

{
  "email": "john.doe@gmail.com"
}

#### Update new password endpoint
PATCH  http://localhost:3001/v1/user/reset-password
Content-Type: application/json 

{
    "email": "john.doe@gmail.com",
    "pin": 555819,
    "newPassword": "lk3456yt"
}

#### user logout endpoint
DELETE http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbmUuZG9lQGdtYWlsLmNvbSIsImlhdCI6MTYzNzg3MDY3NiwiZXhwIjoxNjM3ODcxNTc2fQ.04NGiXINTzZWlV5-40nDlPQovSGcOP8TDmsHqoc0jaU